# When main branch is updated via direct push or PR, use packwiz to
# create a new Prism instance with bundled packwiz-installer-bootstrap.jar
# and upload as a build artifact
name: Build new Prism instance zip
on:
  push:
    branches:
      - 'main'
    paths:
      - 'packs/*/client/**'
  pull_request:
    paths:
      - 'packs/*/client/**'

jobs:
  build-prism-instance:
    # As I understand, all runners can ONLY be one of the runner virtual 
    # machine images supplied by GitHub (or a self-hosted runner but that's 
    # a much later venture)
    runs-on: ubuntu-latest
    steps:

      # 1. Grab packwiz binary from their repo's workflow artifacts
      # - name: Fetch packwiz binary from packwiz repo's workflow artifacts
      #   run:

      # 2. Check out
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
